const mockAPI = {
    async getDashboardKPIs() {
        return {
            totalSKUs: 8,
            totalStores: 4,
            lowStockCount: 6,
            forecastAccuracy: 87.5,
            co2Saved: 245.7,
            stockTurnover: 12.3,
            totalRevenue: 125000,
            fulfillmentRate: 94.2,
        };
    },

    async getInventory() {
        return [
            {
                productId: 1,
                storeId: 1,
                currentStock: 25,
                productName: "iPhone 15",
                category: "Electronics",
                price: 999,
                storeName: "Downtown Store",
                minStock: 10,
                maxStock: 100,
                status: "OK",
                restockAmount: 0,
            },
            {
                productId: 2,
                storeId: 1,
                currentStock: 5,
                productName: "Samsung Galaxy S24",
                category: "Electronics",
                price: 899,
                storeName: "Downtown Store",
                minStock: 8,
                maxStock: 80,
                status: "LOW",
                restockAmount: 75,
            },
            {
                productId: 3,
                storeId: 1,
                currentStock: 12,
                productName: "MacBook Pro",
                category: "Electronics",
                price: 1999,
                storeName: "Downtown Store",
                minStock: 5,
                maxStock: 50,
                status: "OK",
                restockAmount: 0,
            },
            {
                productId: 4,
                storeId: 1,
                currentStock: 45,
                productName: "Organic Milk",
                category: "Food",
                price: 4.99,
                storeName: "Downtown Store",
                minStock: 50,
                maxStock: 200,
                status: "LOW",
                restockAmount: 155,
            },
            {
                productId: 5,
                storeId: 2,
                currentStock: 25,
                productName: "Frozen Pizza",
                category: "Food",
                price: 8.99,
                storeName: "Mall Branch",
                minStock: 30,
                maxStock: 150,
                status: "LOW",
                restockAmount: 125,
            },
            {
                productId: 6,
                storeId: 3,
                currentStock: 8,
                productName: "Insulin Pen",
                category: "Pharma",
                price: 89.99,
                storeName: "Suburb Store",
                minStock: 20,
                maxStock: 100,
                status: "LOW",
                restockAmount: 92,
            },
            {
                productId: 8,
                storeId: 2,
                currentStock: 10,
                productName: "Wireless Headphones",
                category: "Electronics",
                price: 199,
                storeName: "Mall Branch",
                minStock: 15,
                maxStock: 75,
                status: "LOW",
                restockAmount: 65,
            },
        ];
    },

    async getForecast(productId) {
        return {
            productId,
            productName: "iPhone 15",
            forecast: {
                nextWeekDemand: 28,
                confidence: 0.87,
                trend: "increasing",
                recommendation: "Increase stock order",
            },
            historicalData: [
                { date: "2024-06-15", actual: 8, predicted: null },
                { date: "2024-06-20", actual: 12, predicted: null },
                { date: "2024-06-25", actual: 15, predicted: null },
                { date: "2024-07-01", actual: 18, predicted: null },
                { date: "2024-07-05", actual: 22, predicted: null },
                { date: "2024-07-10", actual: 25, predicted: null },
                { date: "2024-07-15", actual: null, predicted: 28 },
                { date: "2024-07-20", actual: null, predicted: 29 },
                { date: "2024-07-25", actual: null, predicted: 31 },
            ],
        };
    },

    async getColdChainStatus() {
        return {
            trucks: [
                {
                    id: 1,
                    name: "Truck Alpha",
                    currentTemp: 2.5,
                    targetTemp: 2.0,
                    status: "active",
                    route: "Store 1 → Store 2",
                    lat: 40.73,
                    lng: -74.02,
                    cargo: ["Organic Milk", "Frozen Pizza"],
                },
                {
                    id: 2,
                    name: "Truck Beta",
                    currentTemp: 8.5,
                    targetTemp: 5.0,
                    status: "warning",
                    route: "Warehouse A → Store 3",
                    lat: 40.71,
                    lng: -73.99,
                    cargo: ["Insulin Pen", "Organic Milk"],
                },
                {
                    id: 3,
                    name: "Truck Gamma",
                    currentTemp: 15.2,
                    targetTemp: 2.0,
                    status: "critical",
                    route: "Store 2 → Store 3",
                    lat: 40.765,
                    lng: -73.98,
                    cargo: ["Frozen Pizza", "Organic Milk"],
                },
            ],
            summary: {
                totalTrucks: 3,
                activeAlerts: 2,
                criticalAlerts: 1,
                avgTemperature: 8.7,
            },
        };
    },

    async getRouteOptimization() {
        return {
            routes: [
                {
                    id: 1,
                    from: "Warehouse A",
                    to: "Downtown Store",
                    distance: "12.5 km",
                    estimatedTime: "25 minutes",
                    fuelCost: 8.5,
                    optimized: true,
                },
                {
                    id: 2,
                    from: "Downtown Store",
                    to: "Mall Branch",
                    distance: "8.3 km",
                    estimatedTime: "18 minutes",
                    fuelCost: 6.2,
                    optimized: true,
                },
            ],
            optimizationSummary: {
                totalDistance: "20.8 km",
                totalTime: "43 minutes",
                totalFuelCost: 14.7,
                co2Reduction: "23.5 kg",
                timesSaved: "12 minutes",
            },
        };
    },
};

export default mockAPI;
